[package]
name = "slidetown-gui"
version = "0.1.0"
authors = ["amPerl"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
camino = { version = "1.0.9", features = ["serde1"] }
eframe = { version = "0.18.0", features = ["persistence"] }
native-dialog = "0.6.3"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.82"
slidetown = { path = '../slidetown' }
