[package]
name = "slidetown-gui"
version = "0.1.0"
authors = ["amPerl"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.11.0"
native-dialog = "0.5.5"
slidetown = { path = '../slidetown' }
